"""empty message

Revision ID: 06930840796c
Revises: 
Create Date: 2026-03-17 15:41:54.173829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '06930840796c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarea_completada'), ['completada'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_prioridad'), ['prioridad'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarea_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tarea_titulo'))
        batch_op.drop_index(batch_op.f('ix_tarea_prioridad'))
        batch_op.drop_index(batch_op.f('ix_tarea_completada'))

    op.drop_table('tarea')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
